name: let_tutor_mobile
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.4.0
  ##framework
  get: ^4.6.5

  ## feature
  dio: ^5.1.1
  flutter_secure_storage: ^8.0.0
  intl: ^0.17.0

  ## UI
  multiselect: ^0.1.0
  multi_select_flutter: ^4.1.3

  # from chat gpt dependency
  provider: ^6.0.5

  ##generate json
  json_annotation: ^4.8.1

  ## enviroment
  flutter_dotenv: ^5.0.2

  ## UI
  flutter_spinkit: ^5.1.0
  avatar_glow: ^2.0.2
  ###quick setting screen
  settings_ui: ^2.0.2

  ## save chat
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.0

  ## Feature
  flutter_tts: ^3.6.3
  speech_to_text: ^6.1.1
  flutter_easyloading: ^3.0.5
  flick_video_player: ^0.5.0
  video_player: ^2.6.1
  flutter_svg: ^2.0.5
  http: ^0.13.6
  google_sign_in: ^6.1.0
  firebase_core: ^2.13.0
  firebase_auth: ^4.6.1
  advance_pdf_viewer:
    git:
      url: https://github.com/lohanidamodar/pdf_viewer.git
      ref: 4e5d96be29de515f1081c0b6897741b8dca84722
  image_picker: ^0.8.7+5
  country_picker: ^2.0.20
  firebase_crashlytics: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/launcherIcons/ic_launcher.png"
  adaptive_icon_background: "assets/launcherIcons/ic_launcher_background.png"
  adaptive_icon_foreground: "assets/launcherIcons/ic_launcher_foreground.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/images/
    - .env

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
