// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrt3LEu-ExloSvuZOPycQiiXMr1uY_kE0',
    appId: '1:116994020586:android:d478198ca3925d58d33393',
    messagingSenderId: '116994020586',
    projectId: 'let-tuttor',
    storageBucket: 'let-tuttor.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADL9hJIrmGayOIXxVdb4WHjedgNBVC610',
    appId: '1:116994020586:ios:4877727fb610dde6d33393',
    messagingSenderId: '116994020586',
    projectId: 'let-tuttor',
    storageBucket: 'let-tuttor.appspot.com',
    androidClientId: '116994020586-jd9do7gfrcs1aufg0dpbnhoj5qdieiu4.apps.googleusercontent.com',
    iosClientId: '116994020586-oj383ob2vc7fd57vaii8lnb3h60nk0ai.apps.googleusercontent.com',
    iosBundleId: 'vn.zabittank.letTutorMobile',
  );
}
